version: '3.8'

services:

  app_campamentos:
    build: .
    ports:
      - '3001:3001'
    links: 
      - dbd_campamentos
    volumes:
      - .:/app
    expose:
      - 3001

  dbd_campamentos: 
    image: mysql:latest
    restart: always
    ports:
      - '3308:3306'
    container_name: dbd_campamentos
    environment:
      - MYSQL_ROOT_PASSWORD=dante569
    volumes:
      - volume_campamentos:/var/lib/data

volumes:
  volume_campamentos:
